language: go
go:
- 1.13
env:
  global:
  - GOOS=linux
install:
- go get -t ./...
script:
- mv $GOPATH/bin/undocker-dns ./
- md5sum undocker-dns > md5.txt
- md5sum undocker-dns.service >> md5.txt
- sha256sum undocker-dns > sha256.txt
- sha256sum undocker-dns.service >> sha256.txt
- sha512sum undocker-dns > sha512.txt
- sha512sum undocker-dns.service >> sha512.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZRHPN5E2bzSmKeVol8vuWCx5rkUqBslf5HryZk9rzx48bvCE6+AKW2u02rVzZRt2bSgjwMy1lb4SrIhMvyXTty7XkTgI077iEy6TWA1QjSEC3244BWxWj1rPjjYIcvgqYhC30c5uha7wI3x8pGFUL4rywus8jkYWNGYbV4Y4IxfraGfCurr40M7yXKEl6eUWnGdGR5me7G2aeEcQ72JAtyEOLwh+v1t7dDSwc7RkxM+GlamU8MH/YnwxnAUjSFLOhsDtnYNrssB6OoxDgA9N07rR5SjZofwgbFcIQIsell2mEqvAphqXsODrVx45T3hmjA4LrcBZrHuzw1aYXnDDrVcQIuUnwTROV6iQmXofXZgaePUVWzSq4YR2q7XLBO5h/m4lvrl5q+5jYtrZGifUp+xwIlCBRrBbocK8F7CFg7seTjt0a29FAhMGef32OyJPlXtBhZuWe7m/77wajCkrm+8XIlFDc1r1hGpcV2AyhqAdBGgUgZRZUD6hDmt6q4jA5XQvBXY3eU2ZOH4gVX0BOB0rtNHJBSFzXDk170cid4CvO4xjEsJP3mRu5+Veke0jmLJBOTLE4E3FQZD5kf6+l3ta3RxFR4qys1bNWIkblbMHc8ModOfjsKPFOcIPAg0F2JxmiqrqxbJA6hCDIf21v5l9d239Mt8+hnPLyMXrFgQ=
  file:
  - undocker-dns
  - undocker-dns.service
  - md5.txt
  - sha256.txt
  - sha512.txt
  on:
    tags: true
